/*
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// Types
export type {
  ActionContext,
  ActionResult,
  CellValue,
  Column,
  ColumnAffinity,
  ColumnConfig,
  ConstraintMode,
  Database,
  DisplayType,
  ExecutionContextLike,
  ForeignKey,
  HookContext,
  OptionSchema,
  PreparedStatement,
  RequestOverrides,
  RouteHandler,
  RowAction,
  RowPatch,
  TableHooks,
  TapemarkBaseOptions,
  RowData,
  RowResult,
  Schema,
  Table,
  TableConfig,
  TableOptions,
  TapemarkContext,
  TapemarkOptions,
  TapemarkRequest,
  TapemarkResponse,
  ThemeName,
} from "./types";

// Themes
export { themes, defaultTheme } from "./themes";
export type { ThemeDefinition } from "./themes";

// Errors
export { NotFoundError, TapemarkError, ValidationError } from "./errors";

// Schema introspection
export {
  isAutoGeneratedPk,
  isInternalTable,
  NameValidationError,
  parseAffinity,
  SchemaIntrospector,
} from "./schema";

// Repository
export {
  castValue,
  decodePk,
  encodePk,
  TableRepository,
} from "./repository";

// Config
export { ConfigStore } from "./config";

// Migrator
export { TapemarkMigrator } from "./migrator";

// Display types
export {
  builtinDisplayTypes,
  createDisplayTypeRegistry,
} from "./display";

// Lookup
export { pickLabelColumn } from "./routes/lookup";

// Core
export { createTapemark } from "./router";
export type { TapemarkCore } from "./router";

// Layout primitives
export { TapemarkLayout } from "./components/TapemarkLayout";
export type { Crumb } from "./components/TapemarkLayout";
export { renderPage } from "./render";

// Database list page
export { renderDatabaseListPage } from "./database-list.jsx";
export type { DatabaseListItem } from "./components/DatabaseListPage";
