import { NotFoundError } from "./errors";
import { computeHash } from "./hash";
import type { Column, ColumnAffinity, Database, ForeignKey, Schema, Table } from "./types";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const SAFE_NAME = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

/** Tables that should never appear in the admin UI. */
const INTERNAL_PREFIXES = ["_tapemark_", "_cf_", "sqlite_"];
const INTERNAL_NAMES = new Set([
  "_cf_METADATA",
  "d1_migrations",
  "sqlite_sequence",
]);

// ---------------------------------------------------------------------------
// Affinity parsing (SQLite rules: https://www.sqlite.org/datatype3.html)
// ---------------------------------------------------------------------------

export function parseAffinity(rawType: string): ColumnAffinity {
  const upper = rawType.toUpperCase();
  if (upper.includes("INT")) return "integer";
  if (
    upper.includes("CHAR") ||
    upper.includes("CLOB") ||
    upper.includes("TEXT")
  )
    return "text";
  if (upper.includes("BLOB") || upper === "") return "blob";
  if (
    upper.includes("REAL") ||
    upper.includes("FLOA") ||
    upper.includes("DOUB")
  )
    return "real";
  return "numeric";
}

// ---------------------------------------------------------------------------
// Name validation
// ---------------------------------------------------------------------------

export function isInternalTable(name: string): boolean {
  if (INTERNAL_NAMES.has(name)) return true;
  return INTERNAL_PREFIXES.some((prefix) => name.startsWith(prefix));
}

/** True for sole-INTEGER-PK columns on rowid tables — SQLite aliases them
 *  to rowid and fills them in on INSERT, so admin UIs typically hide them
 *  on create. `WITHOUT ROWID` tables disable the aliasing, so the column
 *  is a regular integer PK that the user must supply. */
export function isAutoGeneratedPk(
  col: Column,
  primaryKey: string[],
  hasRowid: boolean,
): boolean {
  return (
    hasRowid &&
    primaryKey.length === 1 &&
    primaryKey[0] === col.name &&
    col.affinity === "integer"
  );
}

export class NameValidationError extends NotFoundError {
  constructor(
    public readonly kind: "table" | "column",
    public readonly invalidName: string,
  ) {
    super(
      `${kind} not found: ${invalidName}`,
      `Validated against sqlite_master`,
    );
    this.name = "NameValidationError";
  }
}

// ---------------------------------------------------------------------------
// SchemaIntrospector
// ---------------------------------------------------------------------------

/** Raw PRAGMA table_info row. */
interface PragmaColumnRow {
  cid: number;
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
}

/** Raw PRAGMA foreign_key_list row. */
interface PragmaForeignKeyRow {
  id: number;
  seq: number;
  table: string;
  from: string;
  to: string;
  on_update: string;
  on_delete: string;
}

export class SchemaIntrospector {
  constructor(private db: Database) {}

  /** All user-facing table and view names (excludes internal tables). */
  async getTableNames(): Promise<string[]> {
    const entries = await this.getTableEntries();
    return entries.map((e) => e.name);
  }

  /** All user-facing tables and views with their kind. */
  async getTableEntries(): Promise<{ name: string; kind: "table" | "view" }[]> {
    const rows = await this.db
      .prepare(
        "SELECT name, type FROM sqlite_master WHERE type IN ('table', 'view') ORDER BY type, name",
      )
      .all<{ name: string; type: string }>();
    return rows
      .filter((r) => !isInternalTable(r.name))
      .map((r) => ({ name: r.name, kind: r.type as "table" | "view" }));
  }

  /** Validate that a table or view name exists and is safe to use in SQL. */
  async assertTable(name: string): Promise<void> {
    if (!SAFE_NAME.test(name)) {
      throw new NameValidationError("table", name);
    }
    const names = await this.getTableNames();
    if (!names.includes(name)) {
      throw new NameValidationError("table", name);
    }
  }

  /** Validate that a column belongs to the given table. */
  async assertColumn(table: string, column: string): Promise<void> {
    if (!SAFE_NAME.test(column)) {
      throw new NameValidationError("column", column);
    }
    const info = await this.getTable(table);
    if (!info.columns.some((c) => c.name === column)) {
      throw new NameValidationError("column", column);
    }
  }

  /** Foreign keys for a table (views have none). */
  async getForeignKeys(name: string): Promise<ForeignKey[]> {
    const rows = await this.db
      .prepare(`PRAGMA foreign_key_list("${name}")`)
      .all<PragmaForeignKeyRow>();

    // Group by constraint id, preserving seq order
    const grouped = new Map<number, PragmaForeignKeyRow[]>();
    for (const row of rows) {
      const group = grouped.get(row.id);
      if (group) {
        group.push(row);
      } else {
        grouped.set(row.id, [row]);
      }
    }

    const result: ForeignKey[] = [];
    for (const group of grouped.values()) {
      group.sort((a, b) => a.seq - b.seq);
      result.push({
        columns: group.map((r) => r.from),
        referencedTable: group[0].table,
        referencedColumns: group.map((r) => r.to),
        onUpdate: group[0].on_update,
        onDelete: group[0].on_delete,
      });
    }
    return result;
  }

  /** Full column and PK info for a single table or view. */
  async getTable(name: string): Promise<Table> {
    await this.assertTable(name);

    // Determine if this is a table or view
    const entries = await this.getTableEntries();
    const entry = entries.find((e) => e.name === name);
    const kind = entry?.kind ?? "table";

    const pragmaRows = await this.db
      .prepare(`PRAGMA table_info("${name}")`)
      .all<PragmaColumnRow>();

    const columns: Column[] = pragmaRows.map((row) => ({
      name: row.name,
      rawType: row.type,
      affinity: parseAffinity(row.type),
      nullable: row.notnull === 0,
      defaultValue: row.dflt_value,
      primaryKeyPosition: row.pk > 0 ? row.pk : null,
    }));

    // Views don't have primary keys or foreign keys
    const primaryKey = kind === "view"
      ? []
      : columns
          .filter((c) => c.primaryKeyPosition !== null)
          .sort((a, b) => a.primaryKeyPosition! - b.primaryKeyPosition!)
          .map((c) => c.name);

    const foreignKeys = kind === "view" ? [] : await this.getForeignKeys(name);

    // Detect WITHOUT ROWID by checking the CREATE TABLE SQL
    let hasRowid = kind === "table"; // views never have rowid
    if (kind === "table") {
      const sqlRow = await this.db
        .prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?")
        .bind(name)
        .first<{ sql: string }>();
      if (sqlRow?.sql && /WITHOUT\s+ROWID/i.test(sqlRow.sql)) {
        hasRowid = false;
      }
    }

    const countRow = await this.db
      .prepare(`SELECT COUNT(*) as cnt FROM "${name}"`)
      .first<{ cnt: number }>();

    return {
      name,
      kind,
      hasRowid,
      columns,
      primaryKey,
      foreignKeys,
      rowCount: countRow?.cnt ?? 0,
    };
  }

  /** All user-facing tables with column info and row counts. */
  async getTables(): Promise<Table[]> {
    const names = await this.getTableNames();
    return Promise.all(names.map((n) => this.getTable(n)));
  }

  /**
   * Full schema snapshot including a hash for sync compatibility.
   * The hash is computed from the sorted CREATE TABLE statements.
   */
  async getSchema(): Promise<Schema> {
    const tables = await this.getTables();

    const createStmts = await this.db
      .prepare(
        "SELECT sql FROM sqlite_master WHERE type='table' AND sql IS NOT NULL ORDER BY name",
      )
      .all<{ sql: string }>();

    const concatenated = createStmts.map((r) => r.sql).join("\n");
    const hash = await computeHash(concatenated);

    return { tables, hash };
  }
}

