import { isAutoGeneratedPk } from "../schema";
import type { Column, ColumnConfig, DisplayType, TableConfig } from "../types";

interface ConfigFormProps {
  table: string;
  prefix: string;
  columns: Column[];
  primaryKey: string[];
  config: TableConfig;
  displayTypes: Map<string, DisplayType>;
}

export function ConfigForm({
  table,
  prefix,
  columns,
  primaryKey,
  config,
  displayTypes,
}: ConfigFormProps) {
  const displayOptions = Array.from(displayTypes.keys());

  // Serialize display type schemas for the web component
  const schemas: Record<string, unknown> = {};
  for (const [name, dt] of displayTypes) {
    schemas[name] = dt.schema;
  }
  const schemasJson = JSON.stringify(schemas);

  return (
    <form
      method="post"
      action={`${prefix}/${table}/_config`}
      class="tm-form tm-form-wide"
    >
      <script
        type="application/json"
        id="tm-display-schemas"
        dangerouslySetInnerHTML={{ __html: schemasJson }}
      />
      <table>
        <thead>
          <tr>
            <th>column</th>
            <th>type</th>
            <th>display</th>
            <th>options</th>
            <th>label</th>
            <th>hidden</th>
            <th title="Show on create form (only meaningful for auto-generated INTEGER primary keys)">
              show on create
            </th>
          </tr>
        </thead>
        <tbody>
          {columns.map((col) => {
            const cc: ColumnConfig = config.columns?.[col.name] ?? {};
            const optionsJson = JSON.stringify(cc.options ?? {});
            const isAutoPk = isAutoGeneratedPk(col, primaryKey);
            return (
              <tr>
                <td>{col.name}</td>
                <td class="tm-muted">{col.rawType || "TEXT"}</td>
                <td>
                  <select name={`${col.name}__display`}>
                    {displayOptions.map((opt) => (
                      <option value={opt} selected={cc.display === opt}>
                        {opt}
                      </option>
                    ))}
                  </select>
                </td>
                <td>
                  <tm-display-options
                    data-column={col.name}
                    data-options={optionsJson}
                  />
                </td>
                <td>
                  <input
                    name={`${col.name}__label`}
                    value={cc.label || ""}
                    placeholder={col.name}
                  />
                </td>
                <td class="tm-center">
                  <input
                    name={`${col.name}__hidden`}
                    type="checkbox"
                    checked={!!cc.hidden}
                    value="1"
                  />
                </td>
                <td class="tm-center">
                  {isAutoPk ? (
                    <input
                      name={`${col.name}__showOnCreate`}
                      type="checkbox"
                      checked={!!cc.showOnCreate}
                      value="1"
                    />
                  ) : (
                    <span class="tm-muted">—</span>
                  )}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
      <div class="tm-actions">
        <button type="submit" class="tm-btn tm-btn-primary">
          save config
        </button>
        <a href={`${prefix}/${table}`} class="tm-btn">
          cancel
        </a>
      </div>
    </form>
  );
}
